### ISSUE TITLE
서버 실행시 `ModuleNotFoundError: No module named 'mybook.book'` 발생

### ISSUE THREAD

**Issue by rkdgusrnrlrl** [hyeongJuKim/MyBook#18]
## 상황
- `python manage.py runserver` 실행 시 다음과 같은 에러 발생
```
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7f8ce19d4e18>
Traceback (most recent call last):
  File "/home/rkdgusrnrlrl/PycharmProjects/MyBook/mybookvenv/lib/python3.6/site-packages/django/utils/autoreload.py", line 225, in wrapper
    fn(*args, **kwargs)
  File "/home/rkdgusrnrlrl/PycharmProjects/MyBook/mybookvenv/lib/python3.6/site-packages/django/core/management/commands/runserver.py", line 113, in inner_run
    autoreload.raise_last_exception()
  File "/home/rkdgusrnrlrl/PycharmProjects/MyBook/mybookvenv/lib/python3.6/site-packages/django/utils/autoreload.py", line 248, in raise_last_exception
    raise _exception[1]
  File "/home/rkdgusrnrlrl/PycharmProjects/MyBook/mybookvenv/lib/python3.6/site-packages/django/core/management/__init__.py", line 327, in execute
    autoreload.check_errors(django.setup)()
  File "/home/rkdgusrnrlrl/PycharmProjects/MyBook/mybookvenv/lib/python3.6/site-packages/django/utils/autoreload.py", line 225, in wrapper
    fn(*args, **kwargs)
  File "/home/rkdgusrnrlrl/PycharmProjects/MyBook/mybookvenv/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/rkdgusrnrlrl/PycharmProjects/MyBook/mybookvenv/lib/python3.6/site-packages/django/apps/registry.py", line 120, in populate
    app_config.ready()
  File "/home/rkdgusrnrlrl/PycharmProjects/MyBook/mybookvenv/lib/python3.6/site-packages/django/contrib/admin/apps.py", line 23, in ready
    self.module.autodiscover()
  File "/home/rkdgusrnrlrl/PycharmProjects/MyBook/mybookvenv/lib/python3.6/site-packages/django/contrib/admin/__init__.py", line 26, in autodiscover
    autodiscover_modules('admin', register_to=site)
  File "/home/rkdgusrnrlrl/PycharmProjects/MyBook/mybookvenv/lib/python3.6/site-packages/django/utils/module_loading.py", line 47, in autodiscover_modules
    import_module('%s.%s' % (app_config.name, module_to_search))
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/rkdgusrnrlrl/PycharmProjects/MyBook/mybook/book/admin.py", line 2, in <module>
    from mybook.book.models import Book, User
ModuleNotFoundError: No module named 'mybook.book'
```
## 해결 방법
- 찾아 봐야 할 듯

**Comment by hyeongJuKim** [comment]
모델에 대한 migration이 되었는지 확인.

## 일반 Sell에서
```shell
# 마이그레이션 파일 생성
$ python manage.py makemigrations <app-name>
# 마이그레이션 적용
$ python manage.py migrate <app-name>
```
## Pycharm에서
- Menu -> Tools -> Run manage.py Task
- 여기에서는 manage.py 생략. 명령어만 입력.
- ex) makemigrations <app-name>

**Comment by rkdgusrnrlrl** [comment]
- `python manage.py makemigrations <app-name>` 여기서 app-name 은 book 만들어가면 됨??
- `python manage.py makemigrations book` 시도 해봤고 `ModuleNotFoundError: No module named 'mybook.book'` 에러 발생함 ...살려주  😭 😭 😭

**Comment by rkdgusrnrlrl** [comment]
@hyeongJuKim 형주 문제점을 찾았음 프로젝트 구조를 변경 해야 할 것 같음
- 가장 상위 폴더 날려 버리고
- `manage.py` 있는 폴더가 root 폴더가 되어야 될 것 같음 - 옵션
- 'book' 이 `mybook` 하위로 들어가야 함 - 필수(아마...)
- 아래와 같이 바꾸니 `mybook.book.models` 잘 됨
![image](https://user-images.githubusercontent.com/11402853/36832624-91dd9304-1d6f-11e8-845c-610ab5d578d1.png)

**Comment by hyeongJuKim** [comment]
startproject이랑 startapp을 같은 경로에 해서 생긴 문제인 것 같습니다.ㅎㅎㅎ
죄송염😂

**Comment by hyeongJuKim** [comment]
@rkdgusrnrlrl 폴더 경로 이동하고 풀리퀘스트 부탁드립니다 ㅎㅎ 
pull받아서 저도 테스트 후에 close할게요

**Comment by rkdgusrnrlrl** [comment]
- 지금 방식도 틀린 것은 아님 
  - [장고 공식 튜토리얼](https://docs.djangoproject.com/en/2.0/intro/tutorial01/)을 살펴 보면 `poll` 이라는 앱은 `manage.py` 있는 폴더에 두고  `admin.py` 에서 `from .models import Question` 로 호출 하고 있음
- @hyeongJuKim 그래서 어떤게 좋을 것 같음??

**Comment by hyeongJuKim** [comment]
그럼 저희 하던대로 폴더 이동없이 가시죠 ㅎㅎ
기본으로 하는게 좋을듯👨🏻‍💻

**Comment by rkdgusrnrlrl** [comment]
@hyeongJuKim  그럼 이슈 클로즈??

**Comment by hyeongJuKim** [comment]
넵  close !!!!
